# Generated by Django 5.1.1 on 2024-09-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_products_orderitem_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_item_images/'),
        ),
    ]
