# Generated by Django 5.1.1 on 2024-09-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_cart_items_cart_created_at_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='otal_order_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=50),
        ),
    ]
