# Generated by Django 5.1.1 on 2024-09-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
